generate_seed: 0
target_attr: race
top_k: 0
top_k_list: "30_100_30_30"
edit_ratios: "1.0_5.0_1.5_1.5"
features_saved_path: ./features/P2
num_samples: 10000

use_sae: True
sparse_autoencoder_model_path: ./sae-ckpts

edit_method: multiply_all_probability

model_args_path: ./config/P2/P2_model_config/celeba_hq.yaml
model_path: ./celebahq_p2.pt

sample_dir: "./samples_race"